const RADROOTS_MARKET_RELAY_INDEXES_URL = import.meta.env.VITE_PUBLIC_RADROOTS_MARKET_RELAY_INDEXES_URL;
if (!RADROOTS_MARKET_RELAY_INDEXES_URL || typeof RADROOTS_MARKET_RELAY_INDEXES_URL !== 'string') throw new Error('Missing env var: VITE_PUBLIC_RADROOTS_MARKET_RELAY_INDEXES_URL');

export const _env = {
    RADROOTS_MARKET_RELAY_INDEXES_URL,
} as const;